"""empty message

Revision ID: b827fd51a2e1
Revises: 
Create Date: 2024-09-19 15:47:16.939729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b827fd51a2e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_specialisation',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('specialisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['specialisation_id'], ['specialisation.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'specialisation_id')
    )
    op.create_table('unit_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_type', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=True),
    sa.Column('custom_title_text', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('custom_value', sa.String(length=255), nullable=True),
    sa.Column('is_specialisation', sa.Boolean(), nullable=True),
    sa.Column('unit_set_id', sa.Integer(), nullable=True),
    sa.Column('specialisation_id', sa.Integer(), nullable=True),
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['specialisation_id'], ['specialisation.id'], ),
    sa.ForeignKeyConstraint(['unit_set_id'], ['unit_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_flag', sa.Boolean(), nullable=True),
    sa.Column('capstone_flag', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_element')
    op.drop_table('group')
    op.drop_table('unit_set')
    op.drop_table('course_specialisation')
    op.drop_table('user')
    op.drop_table('unit')
    op.drop_table('specialisation')
    op.drop_table('course')
    # ### end Alembic commands ###
